
spring.thymeleaf.cache: false
resilience4j.retry:
  instances:
    unstableService:
      maxAttempts: 5
      waitDuration: 100
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
#server.port: 0